tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "git"
brew "htop"
brew "neovim"
brew "node"
brew "ranger"
brew "reattach-to-user-namespace"
brew "screenfetch"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "wget"
brew "yadm"
brew "yarn"
brew "zsh"

cask "alfred"
cask "dropbox"
cask "rectangle"
cask "spotify"
cask "vimr"
cask "google-chrome"
cask "iterm2"
cask "rectangle"
cask "slack"
cask "spotify"
cask "firefox"
cask "docker"

cask "font-fira-code"
